name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install --upgrade build twine

      - run: python -m build

      # Se quiser publicar direto no PyPI oficial, altere 'testpypi' para 'pypi'
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.FLAI_PYPITEST_TOKEN }}
        run: |
          twine upload --repository testpypi dist/*

      # 6️⃣ Publicar no PyPI oficial (quando estiver pronto)
      # - name: Publish to PyPI
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      #   run: |
      #     twine upload dist/*
